# Generated by Django 4.1.3 on 2022-11-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produto_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
